move_group: "arm"
planner_id: "PilzLinear"
planning_time: 5.0
eef_step: 0.01                  # 末端插值步长 (m)
jump_threshold: 0.0             # 笛卡尔路径跳跃阈值 (0=禁用)
velocity_scaling: 0.15
acceleration_scaling: 0.15
goal_tolerance: 0.001
ik_solver: "trac_ik"
safety_limit_file: "config/safety_limit.yaml"
