move_group: "arm"               # MoveIt MoveGroup 名称
planner_id: "RRTConnectkConfigDefault"
planning_time: 5.0              # 规划超时时间 (s)
velocity_scaling: 0.2           # 最大速度比例
acceleration_scaling: 0.2       # 最大加速度比例
goal_tolerance: 0.001           # 关节空间容差 (rad)
ik_solver: "moveit_kdl"            # 逆解插件名，可选 moveit_kdl / trac_ik
safety_limit_file: "config/safety_limit.yaml"
joint_limits_file: "config/joint_limits.yaml"
kinematics_file: "config/kinematics.yaml"
