safety_limits:
  max_joint_velocity: 1.57       # rad/s，全局最大关节速度
  max_joint_acceleration: 3.14   # rad/s^2，全局最大关节加速度
  max_joint_torque: 20.0         # Nm，可选，如果有扭矩传感器

  workspace:
    min_xyz: [-1.0, -1.0, 0.0]   # m
    max_xyz: [ 1.0,  1.0, 1.5]   # m

  collision_check:
    enabled: true
    check_resolution: 0.01       # m
