arm:
  kinematics_solver: trac_ik_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  # TRAC-IK specific parameters
  position_only_ik: false  # Set to true for position-only IK (ignore orientation)
  solve_type: Speed        # Options: Speed, Distance, Manipulation1, Manipulation2